language: cpp
sudo: required
compiler:
    - gcc
os:
    - linux

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -q
    - sudo apt-get install gcc-4.8 -y
    - sudo apt-get install g++-4.8 -y
    - sudo apt-get install libgtest* -y
    - cd /usr/src/gtest 
    - sudo cmake . 
    - sudo make 
    - sudo cp libgtest*.a /usr/local/lib

install:
    - mkdir build
    - cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DM32=0 -DUSEKAFKA=0 -DADINFVERSION= -DADINFSOVERSION= -DDEV=1 -DCMAKE_CXX_COMPILER=/usr/bin/g++-4.8 ..

script:
    - make -j 12

notifications:
  email:
      - swansoft_team@groups.163.com
